### PR TITLE
Update README.md and fix deprecated warning

### PR DESCRIPTION
**Pull request by vedangit**
Closes: #51 
Closes: #47 

## What is the purpose of the change

> Adds an introductory link for getting started with terraform using AWS
> Replaces all data.http.myip.body by data.http.myip.response_body in networking.tf

### CODE REVIEW

**Review by tungbq — APPROVED** [review]
Awesome! Thanks for your contribution @vedangit.
Just one comment that in the future I suggest using separated PRs for each issue.

**Comment by vedangit** [comment]
Thank you so much for the advice. Was trying to do so, but couldnt figure out how to create a separate PR for the new commit.

**Comment by tungbq** [comment]
@all-contributors please add @vedangit as code

**Comment by vedangit** [comment]
Ah I see. Thanks a lot!

**Pull request merged**
