### PR TITLE
Add build-web-app-s3-lambda-api-gateway-dynamodb to wishlist

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
Closes: #153
> *Be noted that XXX is the issue ID*

## What is the purpose of the change
[Add build-web-app-s3-lambda-api-gateway-dynamodb to wishlist](https://github.com/tungbq/aws-lab-with-terraform/commit/f23491665dccbfc37c3fce1d60276fd75a51d398)

Hi @tungbq,
just trying to jump on this issue, please check it out

### CODE REVIEW

**Review by tungbq — APPROVED** [review]
LGTM. Thanks @viktoriussuwandi

**Comment by tungbq** [comment]
This branch has conflicts, could you plz check @viktoriussuwandi ?

**Comment by viktoriussuwandi** [comment]
Sorry for that, already solve the conflict @tungbq

**Comment by tungbq** [comment]
Nice! Thanks

**Pull request merged**
