### PR TITLE
Added given hyperlink to "good first issue"

### PR DESCRIPTION
**Pull request by ccchameleon**
Closes: #80 
> *Be noted that XXX is the issue ID*

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documentation of area A by adding ....)*

This pull request adds to the documentation of the existing "CONTRIBUTING.md" file.

### CODE REVIEW

**Comment by tungbq** [comment]
Thanks @ccchameleon for your PR, could you update the PR description to associate with the issue that you are working on?

**Review by tungbq — APPROVED** [review]

**Comment by tungbq** [comment]
@all-contributors please add @ccchameleon as code

**Comment by ccchameleon** [comment]
Thank you for feedback. This is my first PR with open source issues. I believe the PR is now closed so I cannot update the PR description.

**Comment by tungbq** [comment]
@all-contributor please add @Atomicrypt as code

**Comment by tungbq** [comment]
> Thank you for feedback. This is my first PR with open source issues. I believe the PR is now closed so I cannot update the PR description.

No worries, I've updated it already

**Comment by tungbq** [comment]
@all-contributors please add @Atomicrypt as code

**Pull request merged**
